# the project settings file

data_directory_name:
  # the name of the folder containing the compressed backup files
  podcast_republic_backups

Flask:
  # the https interface server configuration
  debug: True
  host: 0.0.0.0
  port: 8080

paths:
  # paths to fetch as part of startup
  [home, project]
